### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Xarond12** [nshoutskiddingservice/Luna-selfbot-source-code#1]
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<obf\luna_platinum_patch.py>", line 2, in <module>
  File "<frozen luna_platinum_patch>", line 48, in <module>
  File "<frozen luna_platinum_patch>", line 48, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "<variables_platinum.py>", line 2, in <module>
  File "<frozen variables_platinum>", line 66, in <module>
  File "<frozen variables_platinum>", line 66, in <module>
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[21628] Failed to execute script 'luna_platinum_patch' due to unhandled exception!

**Comment by PP09PetyaDecryptor** [comment]
ask got for help about this error

**Comment by PP09PetyaDecryptor** [comment]
gpt*
